version: "3.7"
services:

  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.14.0"
    container_name: es01
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=mycluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false # Disable xpack security
      - xpack.security.transport.ssl.enabled=false # Disable transport SSL
    volumes:
      - "es-data-es01:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:9200" ]
      interval: 10s
      timeout: 10s
      retries: 120

  es02:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.14.0"
    container_name: es02
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=mycluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false # Disable xpack security
      - xpack.security.transport.ssl.enabled=false # Disable transport SSL
    volumes:
      - "es-data-es02:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:9200" ]
      interval: 10s
      timeout: 10s
      retries: 120

  es03:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.14.0"
    container_name: es03
    ports:
      - "9202:9200"
      - "9303:9300"
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=mycluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false # Disable xpack security
      - xpack.security.transport.ssl.enabled=false # Disable transport SSL
    volumes:
      - "es-data-es03:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:9200" ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200","http://es03:9200"]'

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.0
    container_name: logstash
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./goldhubBuyer_template.json:/usr/share/logstash/pipeline/template/goldhubBuyer_template.json
      - ./postgresql-42.2.29.jar:/usr/share/logstash/logstash-core/lib/jars/postgresql-42.2.29.jar
    environment:
      - xpack.monitoring.enabled=false
volumes:
  es-data-es01:
    driver: local
  es-data-es02:
    driver: local
  es-data-es03:
    driver: local
